In [1]:
import numpy as np
from scipy.sparse import csr_matrix, kron, eye
from scipy.sparse.linalg import eigsh

# Define parameters for the Hubbard model
SIZE = 4  # Number of sites
J_hopping = 1.0  # Hopping term coefficient
U_onsite = 4.0  # On-site interaction term coefficient

# Define Pauli matrices and spin operators as sparse matrices
I = csr_matrix([[1, 0], [0, 1]])
S_plus = csr_matrix([[0, 1], [0, 0]])  # Raising operator
S_minus = csr_matrix([[0, 0], [1, 0]])  # Lowering operator
Z = csr_matrix([[1, 0], [0, -1]])
X = csr_matrix([[0,1],[1,0]])
zero = csr_matrix([1,0])
one = csr_matrix([0,1])

hamiltonian = J_hopping*(kron(S_plus, kron(I, kron(S_minus, I))) + 
                        kron(S_minus, kron(I, kron(S_plus, I)))+ 
                        kron(I, kron(S_plus, kron(I, S_minus))) + 
                        kron(I, kron(S_minus, kron(I, S_plus)))) + U_onsite*(kron(Z, kron(Z, kron (I,I)))+
                        kron(I, kron(I, kron(Z, Z))))

initial_state = kron(zero, kron(zero, kron(zero, zero)))
initial_state_bra = initial_state.transpose()

In [6]:
state1 = hamiltonian.multiply(initial_state)
state2 = initial_state_bra.multiply(state1)
state2.todense()

matrix([[4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

In [21]:
# Define Pauli matrices and spin operators as sparse matrices
I = np.array([[1, 0], [0, 1]])
S_plus = np.array([[0, 1], [0, 0]])  # Raising operator
S_minus = np.array([[0, 0], [1, 0]])  # Lowering operator
Z = np.array([[1, 0], [0, -1]])
X = np.array([[0,1],[1,0]])
zero = np.array([1,0])
one = np.array([0,1])

hamiltonian = J_hopping*(np.kron(S_plus, np.kron(I, np.kron(S_minus, I))) + 
                        np.kron(S_minus, np.kron(I, np.kron(S_plus, I)))+ 
                        np.kron(I, np.kron(S_plus, np.kron(I, S_minus))) + 
                        np.kron(I, np.kron(S_minus, np.kron(I, S_plus)))) + U_onsite*(np.kron(Z, np.kron(Z, np.kron (I,I)))+
                        np.kron(I, np.kron(I, np.kron(Z, Z))))

In [38]:
initial_state1 = np.kron(one, np.kron(zero, np.kron(zero, zero)))
initial_state2 = np.kron(zero, np.kron(zero, np.kron(one, zero)))

# Reshape initial_state into ket and bra forms
initial_state_ket = initial_state2.reshape(16, 1)           # (16, 1) for column vector (ket)
initial_state_bra = initial_state1.reshape(1,16)            # (1, 16) for row vector (bra)

# Display the shapes to confirm
print("initial_state_ket shape:", initial_state_ket.shape)
print("initial_state_bra shape:", initial_state_bra.shape)

initial_state_ket shape: (16, 1)
initial_state_bra shape: (1, 16)


In [39]:
initial_state_bra @ hamiltonian @ initial_state_ket

array([[1.]])

In [2]:
import numpy as np
from scipy.sparse import csr_matrix, kron, eye
from scipy.sparse.linalg import eigsh

# Define parameters for the Hubbard model
J_hopping = 4 # Hopping term coefficient
U_onsite = 1  # On-site interaction term coefficient

# Define Pauli matrices and spin operators as sparse matrices
I = csr_matrix([[1, 0], [0, 1]])
S_plus = csr_matrix([[0, 1], [0, 0]])  # Raising operator
S_minus = csr_matrix([[0, 0], [1, 0]])  # Lowering operator
Z = csr_matrix([[1, 0], [0, -1]])

# Construct the Hamiltonian for the 2-site Fermi-Hubbard model
hamiltonian = (J_hopping * (
    kron(S_plus, kron(I, kron(S_minus, I))) + 
    kron(S_minus, kron(I, kron(S_plus, I))) +
    kron(I, kron(S_plus, kron(I, S_minus))) + 
    kron(I, kron(S_minus, kron(I, S_plus)))
) + U_onsite * (
    kron(Z, kron(Z, kron(I, I))) +
    kron(I, kron(I, kron(Z, Z)))
))

# hamiltonian = (J_hopping * (
#     kron(S_plus, kron(I, kron(S_minus, I))) + 
#     kron(S_minus, kron(I, kron(S_plus, I))) +
#     kron(I, kron(S_plus, kron(I, S_minus))) + 
#     kron(I, kron(S_minus, kron(I, S_plus)))
# ))

# Define the computational basis states for 4 qubits (2 sites)
basis_states = [
    "|0000>", "|0001>", "|0010>", "|0011>",
    "|0100>", "|0101>", "|0110>", "|0111>",
    "|1000>", "|1001>", "|1010>", "|1011>",
    "|1100>", "|1101>", "|1110>", "|1111>"
]

# Define sectors: for example, (1 up, 1 down) sector
# Here we define the sectors by manually filtering basis states
# In (1 up, 1 down) sector, look for states with exactly one '1' in even positions and one '1' in odd positions

def state_has_particles(state, up_spins, down_spins):
    """Check if a state string has the desired number of up and down spins."""
    up_count = sum(1 for i in range(0, 4, 2) if state[i] == '1')  # Count up spins in even positions
    down_count = sum(1 for i in range(1, 4, 2) if state[i] == '1')  # Count down spins in odd positions
    return up_count == up_spins and down_count == down_spins

# Filter basis states for a specific sector
up_spins = 1
down_spins = 1
sector_indices = [i for i, state in enumerate(basis_states) if state_has_particles(state[1:-1], up_spins, down_spins)]
sector_states = [basis_states[i] for i in sector_indices]

# Extract the submatrix corresponding to the sector from the full Hamiltonian
hamiltonian_dense = hamiltonian.toarray()  # Convert to dense array for easier slicing
sector_hamiltonian = hamiltonian_dense[np.ix_(sector_indices, sector_indices)]

# Diagonalize the submatrix
eigenvalues, eigenvectors = np.linalg.eigh(sector_hamiltonian)

print(f"Basis states for sector with {up_spins} up spin and {down_spins} down spin:", sector_states)
print("Eigenvalues for this sector:", eigenvalues)
print("Eigenvectors for this sector:", eigenvectors)


Basis states for sector with 1 up spin and 1 down spin: ['|0011>', '|0110>', '|1001>', '|1100>']
Eigenvalues for this sector: [-8.24621125 -2.          2.          8.24621125]
Eigenvectors for this sector: [[-4.35162146e-01  0.00000000e+00 -7.07106781e-01 -5.57345410e-01]
 [ 5.57345410e-01 -7.07106781e-01  1.22663473e-17 -4.35162146e-01]
 [ 5.57345410e-01  7.07106781e-01  1.22663473e-17 -4.35162146e-01]
 [-4.35162146e-01  0.00000000e+00  7.07106781e-01 -5.57345410e-01]]


In [7]:
# Compute eigenvalues using scipy.sparse.linalg.eigsh
num_eigenvalues = 15  # Number of eigenvalues to compute
eigenvalues, _ = eigsh(hamiltonian, k=num_eigenvalues, which='SA')  # 'SA' means smallest algebraic

print("Eigenvalues:", eigenvalues)


Eigenvalues: [-4.47213595 -4.         -4.         -4.         -1.         -1.
 -1.         -1.          1.          1.          1.          1.
  4.          4.          4.        ]


In [5]:
# Compute eigenvalues and eigenvectors
num_eigenvalues = 15  # Number of eigenvalues to compute
eigenvalues, eigenvectors = eigsh(hamiltonian, k=num_eigenvalues, which='SA')  # 'SA' means smallest algebraic

# Display eigenvalues
print("Eigenvalues:", eigenvalues)

# Display eigenvectors in the computational basis
print("\nEigenvectors in the computational basis:")
for i in range(num_eigenvalues):
    print(f"\nEigenvalue {i+1}: {eigenvalues[i]}")
    eigenvector = eigenvectors[:, i].flatten()
    for j, amplitude in enumerate(eigenvector):
        if abs(amplitude) > 1e-2:  # Only print significant components
            basis_state = f"{j:0{SIZE}b}"  # Format as binary with SIZE bits
            print(f"  |{basis_state}> : {amplitude.real:.4f} + {amplitude.imag:.4f}j")

Eigenvalues: [-5.14510796 -4.85952339 -4.1866292  -4.         -1.43366463 -1.
 -1.         -0.57414124  0.57414124  1.          1.          1.43366463
  4.          4.1866292   4.85952339]

Eigenvectors in the computational basis:

Eigenvalue 1: -5.145107963395869
  |0000> : 0.0141 + 0.0000j
  |0001> : 0.1818 + 0.0000j
  |0010> : 0.1818 + 0.0000j
  |0011> : 0.1351 + 0.0000j
  |0100> : -0.0643 + 0.0000j
  |0101> : -0.3175 + 0.0000j
  |0110> : -0.5535 + 0.0000j
  |0111> : -0.0643 + 0.0000j
  |1000> : -0.0643 + 0.0000j
  |1001> : -0.5535 + 0.0000j
  |1010> : -0.3175 + 0.0000j
  |1011> : -0.0643 + 0.0000j
  |1100> : 0.1351 + 0.0000j
  |1101> : 0.1818 + 0.0000j
  |1110> : 0.1818 + 0.0000j
  |1111> : 0.0141 + 0.0000j

Eigenvalue 2: -4.859523388615219
  |0001> : 0.1968 + 0.0000j
  |0010> : -0.1968 + 0.0000j
  |0100> : -0.0405 + 0.0000j
  |0101> : -0.4579 + 0.0000j
  |0110> : 0.4579 + 0.0000j
  |0111> : -0.0405 + 0.0000j
  |1000> : 0.0405 + 0.0000j
  |1001> : -0.4579 + 0.0000j
  |1010> : 0.457

In [23]:
eigenvectors[:, 0]

array([-5.55111512e-17, -5.55111512e-17,  0.00000000e+00, -1.62459848e-01,
        2.77555756e-17,  6.38378239e-16,  6.88190960e-01,  0.00000000e+00,
        2.77555756e-17,  6.88190960e-01,  8.32667268e-16,  0.00000000e+00,
       -1.62459848e-01,  0.00000000e+00, -2.77555756e-17, -2.77555756e-17])

In [7]:
from scipy.sparse.linalg import eigsh
from qiskit.quantum_info import Statevector

# Define the initial state |0100> as a Statevector
initial_state = np.zeros(2**SIZE)
# initial_state[4] = 1  # |0100> corresponds to the binary position 4 in decimal
initial_state[12] = 1  # Position 12 corresponds to |1100> in a 4-qubit state
initial_sv = Statevector(initial_state)

# Get eigenvalues and eigenstates of the full Hamiltonian
eigenvalues, eigenvectors = eigsh(hamiltonian, k=15, which='SA')

# Initialize a list to store relevant eigenvalues
relevant_eigenvalues = []

# Calculate the projection of the initial state onto each eigenstate
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T)):
    # Project the initial state onto the eigenstate
    overlap = np.abs(np.dot(initial_sv.data.conj(), eigenvector)) ** 2
    if overlap > 1e-3:  # Filter for significant overlaps
        relevant_eigenvalues.append((eigenvalue, overlap))
        print(f"Eigenvalue: {eigenvalue}, Overlap: {overlap:.4f}")

# The list `relevant_eigenvalues` now contains eigenvalues and overlaps relevant to |0100>


Eigenvalue: -2.82842712474619, Overlap: 0.0732
Eigenvalue: 1.9999999999999998, Overlap: 0.1081
Eigenvalue: 2.0000000000000004, Overlap: 0.0541
Eigenvalue: 2.000000000000001, Overlap: 0.3379


In [3]:
relevant_eigenvalues

[]

In [10]:
# Compute eigenvalues using scipy.sparse.linalg.eigsh
num_eigenvalues = 15  # Number of eigenvalues to compute
eigenvalues, _ = eigsh(hamiltonian, k=num_eigenvalues, which='SA')  # 'SA' means smallest algebraic

print("Eigenvalues:", eigenvalues)


Eigenvalues: [-2.82842712 -2.         -2.         -2.         -1.         -1.
 -1.         -1.          1.          1.          1.          1.
  2.          2.          2.        ]


In [7]:
# Compute all eigenvalues and eigenvectors of the Hamiltonian
eigenvalues, eigenvectors = eigsh(hamiltonian, k=SIZE, which='SA')  # 'SA' for smallest eigenvalues

# Define the computational basis states for the system size
num_qubits = SIZE
basis_states = [f"{i:0{num_qubits}b}" for i in range(2**num_qubits)]  # Generate binary strings as basis states

# Print each eigenvalue with its corresponding eigenstate in the computational basis
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T)):
    print(f"Eigenvalue {i}: {eigenvalue}")
    print("Eigenstate components in computational basis:")
    
    # Go through each component of the eigenvector
    for j, amplitude in enumerate(eigenvector):
        if np.abs(amplitude) > 1e-2:  # Only print significant components
            print(f"  |{basis_states[j]}>: {amplitude:.4f}")
    print()


Eigenvalue 0: -2.8284271247461916
Eigenstate components in computational basis:
  |0011>: -0.2706
  |0110>: -0.6533
  |1001>: -0.6533
  |1100>: -0.2706

Eigenvalue 1: -2.000000000000002
Eigenstate components in computational basis:
  |0101>: 0.6444
  |0110>: 0.5406
  |1001>: -0.5406
  |1010>: 0.0148

Eigenvalue 2: -2.0
Eigenstate components in computational basis:
  |0101>: -0.7494
  |0110>: 0.4492
  |1001>: -0.4492
  |1010>: -0.1865

Eigenvalue 3: -1.9999999999999998
Eigenstate components in computational basis:
  |0101>: -0.1520
  |0110>: 0.0771
  |1001>: -0.0771
  |1010>: 0.9823



In [12]:
from scipy.sparse.linalg import eigsh
from qiskit.quantum_info import Statevector

# Define your initial state |0100> as a Statevector
initial_state = np.zeros(2**SIZE)
initial_state[4] = 1  # |0100> corresponds to the binary position 4 in decimal
initial_sv = Statevector(initial_state)

# Get eigenvalues and eigenstates of the full Hamiltonian
eigenvalues, eigenvectors = eigsh(hamiltonian, k=SIZE, which='SA')

# Calculate the projection of the initial state onto each eigenstate
for i, (eigenvalue, eigenvector) in enumerate(zip(eigenvalues, eigenvectors.T)):
    # Project the initial state onto the eigenstate
    overlap = np.abs(np.dot(initial_sv.data.conj(), eigenvector)) ** 2
    if overlap > 1e-3:  # Filter for significant overlaps
        print(f"Eigenvalue: {eigenvalue}, Overlap: {overlap:.4f}")


In [13]:
eigenvalues

array([-2.82842712, -2.        , -2.        , -2.        ])